services:
  users-service:
    build: ./services/users-service
    container_name: users-service
    ports:
      - "3001:3000"
    volumes:
      - ./services/users-service:/app
    environment:
      - NODE_ENV=development

  crawler-service:
    build: ./services/crawler-service
    container_name: crawler-service
    ports:
      - "3002:3000"
    volumes:
      - ./services/crawler-service:/app

  
