version: "3.9"
services:
  pg_product:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5433:5432"
    volumes:
      - pg_product_data:/var/lib/postgresql/data

  pg_store:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storedb
    ports:
      - "5434:5432"
    volumes:
      - pg_store_data:/var/lib/postgresql/data

  product-service:
    build: ./services/product-service
    env_file:
      - ./services/product-service/.env
    depends_on:
      - pg_product
    ports:
      - "3002:3002"
    command: sh -c "npm run build && npm start"

  store-service:
    build: ./services/store-service
    env_file:
      - ./services/store-service/.env
    depends_on:
      - pg_store
    ports:
      - "3001:3001"
    command: sh -c "npm run build && npm start"

volumes:
  pg_product_data:
  pg_store_data:
