services:
  pg_store:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storedb
    volumes:
      - pg_store_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  pg_product:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    volumes:
      - pg_product_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  service-store:
    build: ./services/store-service
    env_file:
      - ./services/store-service/.env
    depends_on:
      - pg_store
    ports:
      - "3001:3001"

  service-product:
    build: ./services/product-service
    env_file:
      - ./services/product-service/.env
    depends_on:
      - pg_product
    ports:
      - "3002:3002"

volumes:
  pg_store_data:
  pg_product_data:
