export class Product {
  constructor(
    public readonly id: number,
    public readonly name: string,
    public readonly type: string,
    public readonly price: number,
    public readonly storeId: number,
    public readonly createdAt: Date,
  ) {}

  static create(
    name: string,
    type: string,
    price: number,
    storeId: number,
  ): Product {
    if (!name || name.trim().length === 0) {
      throw new Error('Product name is required');
    }
    if (!type || type.trim().length === 0) {
      throw new Error('Product type is required');
    }
    if (price < 0) {
      throw new Error('Price cannot be negative');
    }
    if (storeId <= 0) {
      throw new Error('Store ID must be positive');
    }

    return new Product(
      0, // ID will be generated by database
      name.trim(),
      type.trim(),
      price,
      storeId,
      new Date(),
    );
  }
}