openapi: 3.0.3
info:
  title: Store Service API
  description: API para la gestión de tiendas del comparador de supermercados.
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local development server

tags:
  - name: Stores
    description: Operaciones sobre tiendas

paths:
  /api/stores:
    get:
      tags:
        - Stores
      summary: Obtener todas las tiendas
      responses:
        '200':
          description: Lista de tiendas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Store'

  /api/stores/{id}:
    get:
      tags:
        - Stores
      summary: Obtener tienda por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tienda encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
        '404':
          description: Tienda no encontrada

components:
  schemas:
    Store:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Éxito Buenavista
        baseUrl:
          type: string
          example: https://www.exito.com
        country:
          type: string
          example: CO
        categories:
          type: array
          items:
            type: string
            example: arroz
        isActive:
          type: boolean
          example: true
    StoreCreate:
      type: object
      required: [name, baseUrl, country]
      properties:
        name:
          type: string
          example: Olímpica Prado
        baseUrl:
          type: string
          example: https://www.olimpica.com
        country:
          type: string
          example: CO
        categories:
          type: array
          items:
            type: string
            example: huevo
    StoreUpdate:
      type: object
      properties:
        name:
          type: string
          example: Olímpica Prado Centro
        baseUrl:
          type: string
          example: https://www.olimpica.com
        country:
          type: string
          example: CO
        categories:
          type: array
          items:
            type: string
            example: aceite

