openapi: 3.0.3
info:
  title: Product Service API
  description: API para la gestión de productos del comparador de supermercados.
  version: 1.0.0
servers:
  - url: http://localhost:3002/api
    description: Local development server

tags:
  - name: Products
    description: Operaciones sobre productos

paths:
  /products:
    get:
      tags:
        - Products
      summary: Obtener todos los productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
        - Products
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      tags:
        - Products
      summary: Obtener producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
    put:
      tags:
        - Products
      summary: Actualizar un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
      responses:
        '200':
          description: Producto actualizado correctamente
    delete:
      tags:
        - Products
      summary: Eliminar un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Producto eliminado correctamente

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Arroz Diana
        price:
          type: number
          format: float
          example: 4500.5
        storeId:
          type: integer
          example: 2
    ProductCreate:
      type: object
      required: [name, price, storeId]
      properties:
        name:
          type: string
          example: Arroz Roa
        price:
          type: number
          format: float
          example: 5200
        storeId:
          type: integer
          example: 1
    ProductUpdate:
      type: object
      properties:
        name:
          type: string
          example: Arroz Roa Premium
        price:
          type: number
          format: float
          example: 5300
